name1 = ("candy")
print(name1)
price = input("ราคาสินค่า")
quantity = input("จำนวน")
total_price = (int(price) * int(quantity))
print(int(price) * int(quantity))

name2 = ("milk")
print(name2)
price2 = input("ราคาสินค่า")
quantity2 = input("จำนวน")
total_price2 = (int(price2) * int(quantity2))
print(int(price2) * int(quantity2))
print("ราคารวม" , total_price + total_price2)