name1 = input("กรอกชื่อสินค้า1: ")
price1=input("กรอกราคาสินค้า1: ")
Sales = input("กรอกจำนวนยอดขาย1: ")
total = int(price1) * int(Sales)
print("ยอดรวมสินค้า1: ", total)
name2=input("ชื่อสินค้า2: ")
price2=input("กรอกราคาสินค้า2: ")
Sales2=input("กรอกจำนวนยอดขาย2: ")
total2 = int(price2) * int(Sales2)
print("ยอดรวมสินค้า2: ", total2)
print("ราคาสินค้า1: " +  name1)
print("ราคาของสินค้า1: " + price1)
print("จำนวนยอดขาย1: ", Sales)
print("ชื่อสินค้า2: ", name2)
print("ราคาสินค้า2: ", price2)
print("ยอดขายของสินค้า2: ", Sales2)
print("รวมยอดขายสินค้าทั้งสอง: " + str(total + total2))