name=input("กรอกชื่อของสินค้า1:") 
price1=input("กรอกราคาของสินค้า1:")
Sales = input("กรอกยอดขายของสินค้า1:")
total = int(price1) * int(Sales)
print("ยอดรวมสินค้า1: ", + total)
name2=input("กรอกชื่อของสินค้า2:")
price2=input("กรอกราคาของสินค้า2:")
Sales2=input("กรอกยอดขายของสินค้า2:")
total2 = int(price2) * int(Sales2)
print("ยอดรวมสินค้า2: ", + total2)
print("ชื่อของสินค้า1: " + name)
print("ราคาของสินค้า1: " + price1)
print("ยอดขายของสินค้า1: " + Sales)
print("ชื่อของสินค้า2: " + name2)
print("ราคาของสินค้า2: " + price2)
print("ยอดขายของสินค้า2: " + Sales2)
print("รวมราคาสินค้าทั้งสอง: " + str(total + total2))