name1 = input("กรอกชื่อสินค้า1:")
number1 = input("กรอกราคาสินค้า1:")
number2 = input("กรอกจำนวณยอดขาย1:")
total1 = int(number1)* int(number2)
name2 = input("กรอกชื่อสินค้า2:")
number3 = input("กรอกราคาสินค้า2:")
number4 = input("กรอกจำนวณยอดขาย2:")
total2 = int(number3)* int(number4)
print("ชื่อสินค้า1:"+ name1)
print("ราคาสินค้า1:"+number1)
print("จำนวณยอดขาย:"+number2)
print("ชื่อสินค้า2:"+name2)
print("ราคาสินค้า2:"+number3)
print("ยอดขาย2:"+number4)
print("ราคารวมสินค้าทั้ง2:"+ str(total1 + total2))
